### ISSUE TITLE
Help needed!

### ISSUE THREAD

**Issue by Cadenboy8** [tmarenko/twitch_chat_antiban#12]
Doesn't work. in the twitch chat a user known as Twitch Chat anti-ban just says Twitch Chat Anti-Ban: Connecting to chat server...
Twitch Chat Anti-Ban: Connected to what ever twitch streamer I'm banned from
However Community list, bits, emotes, the chat button and the redeems are all greyed out and can't be selected, nor can i even type in the chat box since where instead of saying "Send a message" it now says "You've been banned from Chat". Hovering over Community simply says "You may not view Users in Chat while banned" While hovering over the redeem simply shows me how many points i have and all the other ones don't show anything. I'm not sure what the "proxy chat" is supposed to be because i can't see anything that would be like that however i can see the chat and that's the only thing that is working. I would like help getting this to work however i don't know how to get it to work nor do i know where to ask for help. I would also like to note that i am on 2.5

**Comment by tmarenko** [comment]
It's the problem on my side because I didn't come up with better description for an extension.
The whole point of this extension is that you could see the chat and messages when you're banned.
Yeah, I picked "anti-ban" wording but unfortunately there is so little that could be done if you're banned.
You can't type, you can't use your channel points, you can't view users. You only can see the chat.

Just to be clear that I've understand you correctly, you see chat **and** messages in the chat, right? If so than this extension is working as intended.

**Comment by Cadenboy8** [comment]
Thanks and yes you understood correctly.

**Comment by tmarenko** [comment]
Sorry for the inconvenience then
This extension just helps to read chat and that's all ¯\_(ツ)_/¯
