### ISSUE TITLE
Can/will this mod support the upcoming Twitch ban change?

### ISSUE THREAD

**Issue by kurtdh** [tmarenko/twitch_chat_antiban#16]
In the next few weeks, Twitch channels will have the option of banning users from WATCHING their streams as well: https://www.techradar.com/gaming/twitch-streamers-will-soon-be-able-to-stop-banned-viewers-from-watching-entirely

My first question is: is it possible for there to be an addon created to avoid this? And my second question is: if it is possible, do you plan on updating this addon? Thanks.

**Comment by tmarenko** [comment]
No promises (it's Twitch **Chat** Antiban😁) but I'll take a look when it comes out.
Could be simple as just to replace with an external player. But they as well might disable the whole channel page completely.

**Comment by kurtdh** [comment]
> No promises (it's Twitch **Chat** Antiban😁) but I'll take a look when it comes out. Could be simple as just to replace with an external player. But they as well might disable the whole channel page completely.

Awesome. If you could keep this open until then, that would be great. If it is possible to bypass, you could always change the name of the addon to just be "Twitch Antiban" instead :)

**Comment by xsmashx88x** [comment]
ya this stopped working :(

**Comment by kurtdh** [comment]
I can't confirm if this addon is still working for chat or not. But now is a good time to ask if it's possible to have it work to view streams too.

**Comment by tmarenko** [comment]
> I can't confirm if this addon is still working for chat or not

It's working for me even if whole stream is banned.

> But now is a good time to ask if it's possible to have it work to view streams too.

Yeah, but will take some time though. The stream page layout is still the same so just need to embed a stream player into the page. Which isn't quite simple since iframe still has the access to user's cookies&storage (so I can't use [the official method](https://dev.twitch.tv/docs/embed/video-and-clips/)).

**Comment by xsmashx88x** [comment]
> > I can't confirm if this addon is still working for chat or not
> 
> It's working for me even if whole stream is banned.
> 
> > But now is a good time to ask if it's possible to have it work to view streams too.
> 
> Yeah, but will take some time though. The stream page layout is still the same so just need to embed a stream player into the page. Which isn't quite simple since iframe still has the access to user's cookies&storage (so I can't use [the official method](https://dev.twitch.tv/docs/embed/video-and-clips/)).

how is it working for you? when its not for anyone else hmm  https://gurzil.shx.gg/6iaWziBIO.png

**Comment by zeus1921** [comment]
+1

**Comment by xsmashx88x** [comment]
> +1

??

**Comment by tmarenko** [comment]
> how is it working for you? when its not for anyone else hmm https://gurzil.shx.gg/6iaWziBIO.png

This extension works only for the chat. I meant that the chat proxy works as usual even if video stream banned.

> The stream page layout is still the same so just need to embed a stream player into the page

Looks like it's not that easy to do. Both original method doesn't work since twitch still can check if your account is banned. Embedding through 3rd-party proxy doesn't work since twitch probably thinks it's a viewbot.

The only working way I found is to inject a [hls.js](https://github.com/video-dev/hls.js) player with twitch's HLS stream. The player probably wouldn't have an ability to select quality and the stream will have ads as well. Codewise, the solution also will introduce 2 external dependencies (the player and API to get twitch's hls playlist). Which in the future could be hard to maintain and support this feature so on.

**Comment by tmarenko** [comment]
I've added support for the stream player as well in https://github.com/tmarenko/twitch_chat_antiban/commit/c36f63bfd0d9fc63c7112b51eb50514360fa3760
New 3.0 version will be out as soon as Chrome/Firefox stores review it.

I think I covered pretty much all of the scenarios (opening multiple banned streams, switching between banned and unbanned streams) but still there is a room for mistake.
Currently the player will automatically switch video quality and will show you the ads (nothing I can do about).

**Please send me any encountered errors right here in this issue.**

**Comment by icynstant** [comment]
> FYI 3.0 is released for Chrome and Firefox

I still can't see chat, I'll give all info in #13
