### ISSUE TITLE
Addon connecting and disconnecting repeatedly on twitchtheater.tv (bug)?

### ISSUE THREAD

**Issue by kurtdh** [tmarenko/twitch_chat_antiban#17]

**Comment by tmarenko** [comment]
Shouldn't be related to `twitchtheater.tv` as it simply opens an iframe to the actual twitch chat.
Does this issue occur frequently (every 5-10 seconds) or just periodically (every 5-10 minutes or so)?
The problem likely is a bad connection to the Twitch chat IRC websocket. This could be due to a slow wifi/internet connection on your end or server issues on twitch's side.

**Comment by kurtdh** [comment]
It happens every couple of minutes it seems. I know it's not on my end. I use wired 1 gig ethernet with a ping window running the entire time with no packet loss. So it has to be Twitch side.

**Comment by tmarenko** [comment]
Not much can be done from extension side if the connection is unstable.
I could suppress "Disconnected ... Connected" messages if reconnection happens quickly. So at least it won't be an eyesore in the chat

**Comment by tmarenko** [comment]
Added the change at other branch: https://github.com/tmarenko/twitch_chat_antiban/compare/master...supress-reconnection-logs
@kurtdh if you could please test the extension:

- [src-2.11.zip](https://github.com/tmarenko/twitch_chat_antiban/files/12565524/src-2.11.zip)

You can just drag & drop the archive to Extension tab. Don't forget to disable 2.10 extension from Chrome Store before testing this one.
I've added 5 sec timeout threshold for reconnection. So on quick reconnects it won't spam logs in the chat

**Comment by tmarenko** [comment]
It also seems that I'm not properly handling keepalive messages, which is probably the reason why twitch disconnects the client. This portion of the code never runs because the command is parsed incorrectly:
https://github.com/tmarenko/twitch_chat_antiban/blob/c4001c1e389c243c65fe5989b365e97df6b5afa5/src/proxy-chat.js#L273-L274

**Comment by tmarenko** [comment]
Fix is [merged](https://github.com/tmarenko/twitch_chat_antiban/pull/18) and released. Please update to 2.11 version

**Comment by kurtdh** [comment]
Ok please leave issue open until I confirm fixed. Thanks.

**Comment by kurtdh** [comment]
Now the addon doesn't work at all on twitchtheater.tv. It just says "You are banned from Chat" and doesn't create any iframe.

**Comment by kurtdh** [comment]
![image](https://github.com/tmarenko/twitch_chat_antiban/assets/26121469/27ed1660-cdb2-401b-8c74-3e97dd57049d)
![image](https://github.com/tmarenko/twitch_chat_antiban/assets/26121469/880e0598-dd01-4df4-b240-b4f76172991b)

Not working for me. Here's some screenshots. Anything else I can do to get this working?

**Comment by kurtdh** [comment]
I figured it out. I had to go into addon settings for your addon, click permissions, and turn on the slider next to access your data for sites in the *://twitch.tv domain. This fixed it for both twitch.tv and twitchtheater.tv

Maybe you should update the text "This extension automatically opens a proxy chat to channels where you are banned." because it's not automatic without turning on that slider first..

**Comment by tmarenko** [comment]
It is automatic for twitch:
https://github.com/tmarenko/twitch_chat_antiban/blob/3350d02abc7c085f7c32fe6e4e64f991e49297c0/src/manifest.json#L14
My guess is that you're using Firefox since it doesn't inject content scripts everywhere (even with `all_frames": true`) and the user also must manually confirm the permissions: https://discourse.mozilla.org/t/are-content-scripts-not-automatically-injected-anymore-with-manifest-v3/108146/2
<img width="256" alt="image" src="https://github.com/tmarenko/twitch_chat_antiban/assets/31345208/97f12bfd-9cd9-49d0-8a59-907d42843113">

Works well on Chrome without any additional settings.

I don't think that I want to add instructions for users of how to use their browser properly.
But maybe just for Firefox I could downgrade manifest version to 2 (since they still support it for some reason)

**Comment by kurtdh** [comment]
Yep, using Firefox. I didn't have this issue prior to this version though, so that's weird.

**Comment by tmarenko** [comment]
Switched to V2 for Firefox: https://github.com/tmarenko/twitch_chat_antiban/commit/9efce137ece89819d52b67884cffda6d77a076e8
Released as `2.11.1` version: https://addons.mozilla.org/en-US/firefox/addon/twitch-chat-anti-ban/versions/

**Comment by kurtdh** [comment]
Original issue seems fixed, it no longer spams. Closing issue now.
