### ISSUE TITLE
Support of undocumented Twitch GraphQL API

### ISSUE THREAD

**Issue by lnoss** [tmarenko/twitch_chat_antiban#22]
Twitch could easily condemn this extension using the ban evasion argument, even if the extension just let banned users the possibility to read back the chat. And the global ban being pushed by Twitch to even block the stream feed implies that they might be going in this direction? But we're not here to discuss the merits of these measures. 

On this basis, the extension existence is already problematic even before it's used.

Based on this principle, why not use Twitch GraphQL API? It's an internal API, so again, Twitch could easily say that using it is at the developers' own risk – and forbidden when the uses are not to their liking. But we don't really care? The main feature of the extension is working: display back the chat. I propose to support the undocumented Twitch GraphQL API to add secondary features to enhance the proxy-chat. It means a bit of retro-engineering behind `https://gql.twitch.tv/gql`.

- Big advantage, we don't need to handle authentication. We can just use the `Client-Id` already used by the frontend. Same for the bearer token.
- Disadvantage, usages could break anyday.

At the moment, I'm only thinking of supporting it to simulate UserCards displayed when a user clicks on an username on the non-banned chat view. I haven't looked at the API schema, but I'm sure other improvements could be implemented with this API.

**Comment by lnoss** [comment]
Just saw the stream proxy source code... I guess we can close it? 😝

**Comment by tmarenko** [comment]
I agree, the major downside is its potential to break at any moment.
Just today, I had to remove it because it stopped returning the stream playlist (my guess it shared the same cookies or metadata of the banned user). I'm open to adding it back, but only if it becomes necessary for a new feature and there's no alternative way to implement that feature without GQL.

I'll close this issue for now, but if you have any suggestions, please let me know!
