### ISSUE TITLE
Video doesn't show when banned on twitchtheater.tv

### ISSUE THREAD

**Issue by kurtdh** [tmarenko/twitch_chat_antiban#24]
The chat shows just fine on twitchtheater.tv, but video does not play. Video plays fine on twitch.tv

**Comment by tmarenko** [comment]
Thanks for noticing!
There were two problems:

- `getPlaylist` couldn't properly retrieve the stream's playlist. Switching to an external API helped.
- There was an edge case where the stream's channel could only be obtained from URL params (not from the location path like on twitch.tv). Fixed in https://github.com/tmarenko/twitch_chat_antiban/commit/4acff304159954b25dc066d51535cd734dcaae7a

I'll release a new version soon.

**Comment by tmarenko** [comment]
Chrome and Firefox are released. Let me know if the fix works for you

**Comment by kurtdh** [comment]
Yes it works. Thanks! While you're here, I was wondering if it would be possible to have the video player use the default twitch video player? I hate not having access to the settings menu and everything else Twitch has when using the video player embed you use. If you must use it, is it possible to have it swap back to the default one after a certain period of time?

**Comment by tmarenko** [comment]
> I was wondering if it would be possible to have the video player use the default twitch video player?

It could be possible, but I haven't found a way yet due to their custom player. 

Currently, I'm using https://github.com/video-dev/hls.js as a proxy player. 
Customizing the appearance and adding features like a quality selector should be possible, but I haven't explored this yet.

> If you must use it, is it possible to have it swap back to the default one after a certain period of time?

Could you please elaborate? The proxy player should appear only if the channel banned the stream for you. So for any unbanned channel you should see the default twitch player.
